name: CI

on: [push]

jobs:
  # MAUI Android Build
  build-android:
    runs-on: windows-latest
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore 'Sample/NuGet v1000/LocalNotification.Sample/LocalNotification.Sample.csproj'

      - name: Build MAUI Android
        run: dotnet publish 'Sample/NuGet v1000/LocalNotification.Sample/LocalNotification.Sample.csproj' -c Release -f net8.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mauibeach-android-ci-build
          path: 'Sample/NuGet v1000/LocalNotification.Sample/bin/Release/net8.0-android/*Signed.a*'

  # MAUI iOS Build
  build-ios:
    runs-on: macos-13
    name: iOS Build
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Set XCode Version
        shell: bash
        run: |
          sudo xcode-select -s "/Applications/Xcode_14.3.app"
          echo "MD_APPLE_SDK_ROOT=/Applications/Xcode_14.3.app" >> $GITHUB_ENV

      - name: Restore Dependencies
        run: dotnet restore 'Sample/NuGet v1000/LocalNotification.Sample/LocalNotification.Sample.csproj'

      - name: Build MAUI iOS
        run: dotnet build 'Sample/NuGet v1000/LocalNotification.Sample/LocalNotification.Sample.csproj' -c Release -f net8.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mauibeach-ios-ci-build
          path: 'Sample/NuGet v1000/LocalNotification.Sample/bin/Release/net8.0-ios/iossimulator-x64/**/*.app'
